trigger:
- main  # or your branch name

pool:
  name: Default

variables:
  NUM1: '5'
  NUM2: '10'

steps:
- script: |
    echo "Testing Python in PATH"
    python --version
    python add.py
  displayName: 'Run add.py using system Python'
  env:
    NUM1: $(NUM1)
    NUM2: $(NUM2)
